### ISSUE TITLE
Morning session: Peer code review

### ISSUE THREAD

**Issue by Ismailco** [Nemwel-Boniface/AwesomeBooks#3]
Your code is good but we have some comment's you can take into account to improve your project more:
- The add book form is not centered in the mobile version of the site. It will improve the quality if it was responsive 
- The book list section becomes too small on mobiles. I think it will be good if it was responsive.
- The book list section is too small on the desktop view, it would be better if you use "%" or "vw" instead of "px" to give it a width, your design will be more responsive.
-

**Comment by Nemwel-Boniface** [comment]
I have fixed all suggested changes.
